train_file: 'E:\code_backup\image-text\data\data\snli_ve_rebuild\ve_caption_train.json'
val_file: 'E:\code_backup\image-text\data\data\snli_ve_rebuild\ve_caption_dev.json'                
test_file: 'E:\code_backup\image-text\data\data\snli_ve_rebuild\ve_caption_test.json'

image_root: 'E:\code_backup\image-text\data\data\flickr30k'

image_res: 384
batch_size_train: 4 
batch_size_test: 64 

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







