train_file: '/data1/yx/suda/image-text/data/ve_rebuild_data/snli_ve_rebuild/ve_caption_train.json'
val_file: '/data1/yx/suda/image-text/data/ve_rebuild_data/snli_ve_rebuild/ve_caption_dev.json'                
test_file: '/data1/yx/suda/image-text/data/ve_rebuild_data/snli_ve_rebuild/format_annotation.json'

image_root: '/data1/yx/suda/image-text/data/images/flickr30k-images'

image_res: 384
batch_size_train: 16 
batch_size_test: 32 

alpha: 0.4
distill: False
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 5, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}

# Data Augment
mask_patch_rate: 0.7





